# Generated by Django 2.1.7 on 2019-02-23 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_actice',
            new_name='is_active',
        ),
    ]
